appRecetas/urls.py
from django.urls import path, include
from . import views


app_name = 'recetas'


urlpatterns = [
    path("", views.home, name="home"),
    path("recetas/", views.recetas, name="recetas"),
    path("receta/<int:receta_id>/", views.receta_detalle, name="receta_detalle"),   
    path("agregar-recetas/", views.agregar_receta, name="agregar_recetas"),
    path("listar-recetas/", views.listar_recetas, name="listar_recetas"),
    path("modificar-receta/<id>/", views.modificar_receta, name="modificar_receta"),
    path("eliminar-receta/<id>/", views.eliminar_receta, name="eliminar_receta"),
    path('gestionar-usuarios/', views.gestionar_usuarios, name='gestionar_usuarios'),
    path('bloquear-usuario/<int:usuario_id>/', views.bloquear_usuario, name='bloquear_usuario'),
    path('like/<int:post_id>/', views.like, name='like_post'),
    path('post/<int:post_id>/favorito/', views.toggle_favorite, name='toggle_favorite'),
    path('favoritos/', views.favorite_posts, name='favorite_posts'),
    path("busqueda", views.busqueda_funcional, name="busqueda_funcional"),
    path('contacto/', views.contacto, name='contacto'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    
]

recetas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("appRecetas.urls")),
    path("", include("usuarios.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/recetas/lista_recetas.html
{% extends 'components/Layout/base.html' %} 
{% load static %}

{% block content %}

  {% for p in entity %}
      <div class="contenedor_recetas col-12 col-md-8">
        <div class="card">
          <div class="row g-0">
            <div class="card_receta col-md-5">
              <img src="{{ p.image.url }}" class="img-fluid rounded-start image" alt="...">
            </div>
            <div class="col-md-7">
              <div class="card_body_recetas card-body">
                <strong class="d-inline-block mb-2 text-primary">{{ p.category }}</strong>
                <h4 class="mb-0">{{ p.title }}</h4>
                <p class="card-text mb-auto">{{ p.ingredients |truncatewords:30 }}</p>
                <p class="text-muted mt-3">Publicado el {{ p.created|date:"d M Y" }}</p>
                <p class="card-text"><small class="text-muted"><a href="{% url 'recetas:receta_detalle' p.id %}" class="stretched-link">Seguir leyendo</a></small></p>
              </div>
            </div>
          </div>
        </div>
        
        
  {% endfor %}
  <div>
    {% include 'components/paginator.html' %}
  </div>
{% endblock %}

templates/pages/recetas/receta_detalle.html
{% extends 'components/Layout/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Detalle Receta{% endblock %}
{% block content %}

  <div class="container_detalle container-fluid align-items-center justify-content-center">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <article class="recipe-card d-flex align-items-center">
          <h1 class="mb-4">{{ receta.title }}</h1>
          {% if receta.image %}
            <img src="{{ receta.image.url }}" alt="{{ receta.title }}" class="img-fluid rounded mb-4">
          {% endif %}

          <h2>Ingredientes</h2>
          <ul class="mb-4">
            {% for ingrediente in ingredientes %}
              <li>{{ ingrediente.strip }}</li>
            {% endfor %}
          </ul>

          <h2>Instrucciones</h2>
          <ul class="mb-4">
            {% for instruccion in instrucciones %}
              <li>{{ instruccion.strip }}</li>
            {% endfor %}
          </ul>

          {% if receta.tabla %}
            <h2>Tabla Nutricional</h2>
            <img src="{{ receta.tabla.url }}" alt="{{ receta.title }}" class="img-fluid rounded mb-4">
          {% endif %}

        
          
          

          <br><br>

      
          {% if user.is_authenticated %}
          <form action="{% url 'recetas:like_post' receta.id %}" method="post" class="like-form">
            {% csrf_token %}
            <button type="submit" class="btn {% if user in receta.likes.all %}btn-success{% else %}btn-danger{% endif %}">
              <i class="bi bi-heart me-2"></i> 
              <span class="badge">{{ receta.likes.count }}</span>
            </button>
          </form>

          <!-- Botón de Favoritos -->
          {% if not user.is_staff %}
          <form action="{% url 'recetas:toggle_favorite' receta.id %}" method="post" class="favorite-form">
            {% csrf_token %}
            <button type="submit" class="btn {% if user in receta.favorites.all %}btn-warning{% else %}btn-outline-warning{% endif %}">
              <i class="bi bi-star me-2"></i> 
              {% if user in receta.favorites.all %}
                Quitar de Favoritos
              {% else %}
                Añadir a Favoritos
              {% endif %}
            </button>
            {% endif %}
          </form>
        {% else %}
          <p>Debes estar logueado para dar "Me gusta" o añadir a "Favoritos".</p>
        {% endif %}



          {% if user.is_authenticated %}
          <h2 class="pt-5 text-end me-5 pe-4">Comentarios...</h2>

          <form method="post">
              {% csrf_token %}
              {{ form | crispy }}

              {% if form.non_field_errors %}
              
              {% endif %}
              <button type="submit" class="btn btn-primary">Enviar Comentario</button>
              <hr>
          </form>
          
          {% if comments %}
              {% for comment in comments %}
                  <div class="comment mb-3 me-5">
                      <div class="comment-user">
                          {% if comment.user.perfil.avatar %}
                              <img src="{{ comment.user.perfil.avatar.url }}" alt="{{ comment.user.username }}'s avatar" class="rounded-circle me-2" style="width: 40px; height: 40px;">
                          {% else %}
                              <img src="{% static 'avatar/icon.png' %}" alt="Default avatar" class="rounded-circle me-2" style="width: 40px; height: 40px;">
                          {% endif %}
                          <strong>{{ comment.user.username }}</strong>
                      </div>
                      <div class="comment-text">
                        <p>{{ comment.body }}</p>
                        <small class="text-muted">{{ comment.date_added }}</small>
                      </div>
                  </div>
              {% endfor %}
          {% else %}
              <p>No hay comentarios aún... Sé el primero en agregar uno.</p>
          {% endif %}
          {% else %}
            <p>Debes estar logueado para "Comentar"</p>
          {% endif %}

          {% if messages %}
            <script>
              {% for message in messages %}
                Swal.fire({
                  title: '¡Favorito!',
                  text: "{{ message }}",
                  iconHtml: '<i class="fa fa-star" style="color:gold;"></i>',
                  confirmButtonText: 'Aceptar'
                });
              {% endfor %}
            </script>
        {% endif %}


        </article>
      </div>
    </div>
  </div>

{% endblock %}