appRecetas/urls.py
from django.urls import path, include
from . import views


app_name = 'recetas'


urlpatterns = [
    path("", views.home, name="home"),
    path("recetas/", views.recetas, name="recetas"),
    path("receta/<int:receta_id>/", views.receta_detalle, name="receta_detalle"),   
    path("agregar-recetas/", views.agregar_receta, name="agregar_recetas"),
    path("listar-recetas/", views.listar_recetas, name="listar_recetas"),
    path("modificar-receta/<id>/", views.modificar_receta, name="modificar_receta"),
    path("eliminar-receta/<id>/", views.eliminar_receta, name="eliminar_receta"),
    path('gestionar-usuarios/', views.gestionar_usuarios, name='gestionar_usuarios'),
    path('bloquear-usuario/<int:usuario_id>/', views.bloquear_usuario, name='bloquear_usuario'),
    path('like/<int:post_id>/', views.like, name='like_post'),
    path('post/<int:post_id>/favorito/', views.toggle_favorite, name='toggle_favorite'),
    path('favoritos/', views.favorite_posts, name='favorite_posts'),
    path("busqueda", views.busqueda_funcional, name="busqueda_funcional"),
    path('contacto/', views.contacto, name='contacto'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    
]

recetas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("appRecetas.urls")),
    path("", include("usuarios.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
app_name = 'usuarios'

urlpatterns = [
    path('register/',views.register, name="register"),
    path('login/', views.login, name='login'),
    path('logout/',views.exit,name='exit'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path("register/", views.register, name="register"),
    path("perfil/", views.perfil, name="perfil"),
    #Reestablecer contrasena
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'), 
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'), 
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'), 
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

templates/components/footer.html
<footer class="footer">
  <div class="container_footer">
    <div class="row">
      <!-- Columna de Acerca de -->
      <div class="col-md-4 mb-4 mb-md-0">
        <h5>Acerca de Nosotros</h5>
        <p>"RukaSabor" es una aplicación web dedicada a preservar y compartir recetas tradicionales de distintas culturas y regiones. </p>
      </div>
      <!-- Columna de Enlaces Rápidos -->
      <div class="col-md-4 mb-4 mb-md-0">
        <h5>Enlaces Rápidos</h5>
        <ul class="list-unstyled">
          <li><a href="{% url 'recetas:home' %}" class="text-decoration-none">Inicio</a></li>
          <li><a href="{% url 'recetas:recetas' %}" class="text-decoration-none">Recetas</a></li>
          {% if request.user.is_authenticated and not request.user.is_staff %}
          <li class="nav-item">
            <a href="{% url 'recetas:favorite_posts' %}">Mis Favoritos</a>
          </li>
          {% endif %}
          
          {% if request.user.is_staff %}
          <li><a href="{% url 'recetas:listar_recetas' %}" class="text-decoration-none">Administrar Recetas</a></li>
          <li class="nav-item">
            <a href="{% url 'recetas:gestionar_usuarios' %}" class="text-decoration-none">Administrar usuarios</a>
          </li>
          {% endif %}

          {% if request.user.is_authenticated %}
          <li>
            <a href="{% url 'usuarios:perfil' %}" class="text-decoration-none">Perfil</a>
          </li>
          <li class="nav-item">
            <a  href="{% url 'usuarios:exit' %}" class="text-decoration-none"">Salir</a>
          </li>
          {% else %} 
          <li class="nav-item">
            <a href="{% url 'usuarios:login' %} class="text-decoration-none"">Iniciar Sesion</a>
          </li>
          <li class="nav-item">
            <a  href="{% url 'usuarios:register' %} class="text-decoration-none"">Registrarse</a>
          </li>
          {% endif %}

          <form action="https://www.paypal.com/donate" method="post" target="_top">
            <input type="hidden" name="hosted_button_id" value="QAAPPUS9HZWPU" />
            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button"  class="m-3"/>
          </form>
            
        </ul>
      </div>
      <!-- Columna de Contacto -->
      <div class="col-md-4">
        <h5>Contacto</h5>
        <ul class="list-unstyled">
          <li><i class="bi bi-geo-alt footer-icon"></i> Calle Principal 123, Ciudad</li>
          <li><i class="bi bi-telephone footer-icon"></i> +1 234 567 890</li>
          <li class="pb-4"><i class="bi bi-envelope footer-icon"></i> info@ejemplo.com</li>
          <a href="{% url 'recetas:contacto' %}" class="btn-contacto btn btn-danger">Ayuda<i class="bi bi-question-circle"></i></a>
          
        </ul>
      </div>
    </div>
    <!-- Línea separadora -->
    <hr class="my-4">
    <!-- Fila de derechos de autor y redes sociales -->
    <div class="row align-items-center">
      <div class="col-md-6 text-center text-md-start">
          <p class="mb-0">&copy; 2024 RukaSabor. Todos los derechos reservados.</p>
      </div>
    </div>
  </div>
</footer>

templates/components/navbar.html
<nav class="navbar navbar-expand-lg borde mb-2 bg-danger">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'recetas:home' %}">RukaSabor</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{% url 'recetas:home' %}">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/recetas/' %}active{% endif %}" href="{% url 'recetas:recetas' %}">Recetas</a>
        </li>
        {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/listar-recetas/' %}active{% endif %}" href="{% url 'recetas:listar_recetas' %}">Administrar recetas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/gestionar-usuarios/' %}active{% endif %}" href="{% url 'recetas:gestionar_usuarios' %}">Administrar usuarios</a>
          </li>
          <!-- Puedes agregar más opciones para el staff aquí -->
        {% endif %}
        {% if request.user.is_authenticated and not request.user.is_staff %}
        
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/favoritos/' %}active{% endif %}" href="{% url 'recetas:favorite_posts' %}">Mis Favoritos</a>
          </li>
        {% endif %}
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/perfil/' %}active{% endif %}" href="{% url 'usuarios:perfil' %}">Perfil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'usuarios:exit' %}">Salir</a>
          </li>         
        {% else %} 
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/accounts/login/' %}active{% endif %}" href="{% url 'usuarios:login' %}">Iniciar Sesion</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/register/' %}active{% endif %}" href="{% url 'usuarios:register' %}">Registrarse</a>
          </li>
        {% endif %}
        <li class="nav-item dropdown">
      </ul>
      <form class="d-flex align-items-center" method="GET" action="{% url 'recetas:busqueda_funcional' %}">
        {% csrf_token %}
        
        <!-- Campo de texto para buscar por nombre -->
        <input type="text" name="busquedaFuncional" value="{{ searched }}" class="form-control me-2" placeholder="Buscar por nombre..." aria-label="Buscar por nombre">
        
        <!-- Selector de categoría -->
        <select class="form-select me-2" name="categoria">
          <option value="">Todas las categorías</option>
          
            <option value="aperitivo">Aperitivo</option>
          
            <option value="principal">Plato Principal</option>
          
            <option value="postre">Postre</option>
          
            <option value="bebida">Bebida</option>
          
            <option value="pan">Pan y Bollería</option>
          
            <option value="sopa">Sopa y Guiso</option>
          
            <option value="ensalada">Ensalada</option>
          
            <option value="mariscos">Mariscos</option>
          
            <option value="carnes">Carnes</option>
          
            <option value="vegetariano">Vegetariano</option>
          
            <option value="otros">Otros</option>
          
        </select>
        
        <!-- Botón de búsqueda -->
        <button class="btn btn-outline-success-coral" type="submit">
          <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"></path>
          </svg>
        </button>
      </form>
    </div>
  </div>
</nav>

templates/components/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

templates/components/paginator_busqueda.html
{% if resultados.has_other_pages %}
        <!-- Paginador dentro del centro -->
        <div class="d-flex justify-content-center mb-5 pb-5">
          <ul class="pagination">
            {% if resultados.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?busquedaFuncional={{ searched|urlencode }}&categoria={{ categoria_seleccionada }}&page={{ resultados.previous_page_number }}">Anterior</a>
              </li>
            {% endif %}

            {% for page in resultados.paginator.page_range %}
              {% if page == resultados.number %}
                <li class="page-item active" aria-current="page">
                  <a class="page-link" href="?busquedaFuncional={{ searched|urlencode }}&categoria={{ categoria_seleccionada }}&page={{ page }}">{{ page }}</a>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?busquedaFuncional={{ searched|urlencode }}&categoria={{ categoria_seleccionada }}&page={{ page }}">{{ page }}</a>
                </li>
              {% endif %}
            {% endfor %}

            {% if resultados.has_next %}
              <li class="page-item">
                <a class="page-link" href="?busquedaFuncional={{ searched|urlencode }}&categoria={{ categoria_seleccionada }}&page={{ resultados.next_page_number }}">Siguiente</a>
              </li>
            {% endif %}
          </ul>
        </div>
{% endif %}