appRecetas/urls.py
from django.urls import path, include
from . import views


app_name = 'recetas'


urlpatterns = [
    path("", views.home, name="home"),
    path("recetas/", views.recetas, name="recetas"),
    path("receta/<int:receta_id>/", views.receta_detalle, name="receta_detalle"),   
    path("agregar-recetas/", views.agregar_receta, name="agregar_recetas"),
    path("listar-recetas/", views.listar_recetas, name="listar_recetas"),
    path("modificar-receta/<id>/", views.modificar_receta, name="modificar_receta"),
    path("eliminar-receta/<id>/", views.eliminar_receta, name="eliminar_receta"),
    path('gestionar-usuarios/', views.gestionar_usuarios, name='gestionar_usuarios'),
    path('bloquear-usuario/<int:usuario_id>/', views.bloquear_usuario, name='bloquear_usuario'),
    path('like/<int:post_id>/', views.like, name='like_post'),
    path('post/<int:post_id>/favorito/', views.toggle_favorite, name='toggle_favorite'),
    path('favoritos/', views.favorite_posts, name='favorite_posts'),
    path("busqueda", views.busqueda_funcional, name="busqueda_funcional"),
    path('contacto/', views.contacto, name='contacto'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    
]

recetas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("appRecetas.urls")),
    path("", include("usuarios.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/Admin/agregar.html
{% extends 'components/Layout/base.html' %} 
{% load crispy_forms_tags %}

{% block title %}Agregar Receta{% endblock %}

{% block content %} 
  <div class="container-fluid">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="card card_editar_receta">
        <div class="card-body">
          <h2>Nueva Receta</h2>
          <br />
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %} 
            {{ form | crispy }}
            <div class="d-flex justify-content-end">
              <input
                type="reset"
                value="Cancelar"
                class="btn btn-secondary p-1 mx-1" />
              <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/pages/Admin/gestionar_usuarios.html
{% extends 'components/Layout/base.html' %}

{% block title %}Administrar usuarios{% endblock %}

{% block content %}
<div class="mx-3" style="min-height: 80vh; width: 90%;">
  
  <div class="card-body">
    <h2 class="text-center m-1">Gestión de Usuarios</h2>
    <div class="overflow-x-scroll">
      <table class="table table_recetas table-striped table-hover table-responsive-sm my-2">
        <thead>
          <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Estado</th>
            <th>Acción</th>
          </tr>
        </thead>
        <tbody>
          {% for perfil in entity %}
            <tr>
              <td>{{ perfil.usuario.username }}</td>
              <td>{{ perfil.usuario.email }}</td>
              <td>
                {% if perfil.is_blocked %}
                  <span class="badge bg-danger">Bloqueado</span>
                {% else %}
                  <span class="badge bg-success">Activo</span>
                {% endif %}
              </td>
              <td>
                <a href="{% url 'recetas:bloquear_usuario' perfil.usuario.id %}" class="boton btn btn-sm {% if perfil.is_blocked %}btn-outline-success{% else %}btn-outline-danger{% endif %}">
                  {% if perfil.is_blocked %}
                    Desbloquear
                  {% else %}
                    Bloquear
                  {% endif %}
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div>
      {% include 'components/paginator.html' %}
    </div>
  </div>
</div>
{% endblock %}

templates/pages/Admin/listar.html
{% extends 'components/Layout/base.html' %} 

{% block title %}Listar Receta{% endblock %}
{% block content %}
  <div
    class="mx-3"
    style="min-height: 80vh; width:90% ;"
    
    >
    <div class="card-body">
      <h2 class="text-center m-1">Listado de Recetas</h2>

      <a href="{% url 'recetas:agregar_recetas' %}" class="btn btn-outline-success btn-sm">
        Agregar Receta
      </a>
      <div class="overflow-x-scroll">
        <table class="table_recetas table table-striped table-hover table-responsive-sm my-2">
          <tr>
            <th>Título</th>
            <th>Ingredientes</th>
            <th>Instrucciones</th>
            <th>Categoría</th>
            <th>Opciones</th>
          </tr>
          {% for p in entity %}
            <tr>
              <td>{{ p.title | title }}</td>
              <td>{{ p.ingredients | truncatewords:5 }}</td>
              <td>{{ p.instructions | truncatewords:5 }}</td>
              <!-- Muestra solo las primeras 20 palabras -->
              <td>{{ p.category }}</td>
              <!-- Asumiendo que category es un ForeignKey y tiene un campo 'name' -->
              <td>
                <a
                  href="{% url 'recetas:modificar_receta' p.id %}"
                  class="boton btn btn-info btn-sm px-1">
                  Modificar
                </a>
                <a
                  href="{% url 'recetas:eliminar_receta' p.id %}"
                  class="boton btn btn-danger btn-sm px-2">
                  Eliminar
                </a>
              </td>
            </tr>
          {% endfor %}
        </table>
      </div>

      <div>
        {% include 'components/paginator.html' %}
      </div>
  </div>
</div>
{% endblock %}

templates/pages/Admin/modificar.html
{% extends 'components/Layout/base.html' %} 
{% load crispy_forms_tags %} 

{% block title %}Editar Receta{% endblock %}
{% block content %} 
  <div class="container-fluid">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="card card_editar_receta">
        <div class="card-body">
          <h2>Editar Receta</h2>
          <br />
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %} 
            {{ form | crispy }}
            <div class="d-flex justify-content-end">
              <input
                type="reset"
                value="Cancelar"
                class="btn btn-secondary p-1 mx-1" />
              <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}